export type Layer = { name: string; static: string; without: string; needs?: string; tryIt?: { label: string; href: string } };
export type LayerGroup = { name: string; cost: 'low' | 'medium' | 'high' | 'existential'; layers: Layer[] };

// Same fourteen layers, in the original's four groups. "Cost to miss" ratings are our judgement.
export const layerGroups: LayerGroup[] = [
  { name: 'Getting found', cost: 'medium', layers: [
    { name: 'SEO foundations', static: 'Sitemap, meta tags, canonical and JSON-LD come from one layout file and the build. A missing title fails the build.', without: 'Pages search engines cannot read, rank or index properly.', tryIt: { label: 'Open the sitemap', href: '/sitemap-index.xml' } },
    { name: 'Social share previews', static: 'An Open Graph image is rendered at build time for every page. No plugin, no runtime image service.', without: 'A grey box when the link is pasted into Slack or LinkedIn.', tryIt: { label: 'Open the share image', href: '/og/index.png' } },
    { name: 'Redirects & 404s', static: 'A plain-text redirects file at the host edge, plus a 404 page that is just a file. Versioned and reviewable in a diff.', without: 'Broken links, lost traffic and a blank page for a mistyped URL.', tryIt: { label: 'Try /prodcuts', href: '/prodcuts' } },
  ]},
  { name: 'Running the site', cost: 'medium', layers: [
    { name: 'Editorial workflow', static: 'Markdown in git, where pull requests are your revisions. Non-technical editors need a headless CMS.', without: 'Every typo becomes a developer ticket.', needs: 'A CMS: a subscription, or a server you maintain' },
    { name: 'Roles & permissions', static: 'A static site has no users. Who can publish is set in your Git host and, if you add one, your CMS.', without: 'Everyone, or nobody, can publish.', needs: 'Git host and CMS settings' },
    { name: 'Media pipeline', static: 'Images are resized, converted to AVIF or WebP and given dimensions at build time.', without: 'A 14 MB hero photo and a slow page.' },
    { name: 'Forms & lead capture', static: 'A host-level form service such as Netlify Forms, or a serverless function behind a bot check.', without: 'A flooded inbox, or leads that vanish.', needs: 'A form service or a function', tryIt: { label: 'Try the form', href: '/demo/form' } },
  ]},
  { name: 'Managing risk', cost: 'high', layers: [
    { name: 'Security patching', static: 'The host patches its platform. You update build-time dependencies in a pull request and run the audit. No application server of your own to exploit.', without: 'Known holes stay open, and mass exploitation can arrive within hours.', tryIt: { label: 'Knock on /wp-login.php', href: '/wp-login.php' } },
    { name: 'Accessibility', static: 'Semantic HTML plus axe or pa11y in CI, so a regression fails the build instead of reaching users.', without: 'Visitors are locked out, and there is legal exposure.' },
    { name: 'Privacy & consent', static: 'A small open-source consent library gates trackers until a visitor accepts. Astro has no built-in one, but an integration exists.', without: 'Trackers load before anyone has said yes.', needs: 'A consent library, or a hosted platform', tryIt: { label: 'Try the consent demo', href: '/demo/consent' } },
    { name: 'Backups & rollback', static: 'The site is a git repo plus a build, and most hosts keep earlier deploys, so rollback is a click.', without: 'No way back from a bad release.', needs: 'Separate backups for any SaaS CMS content' },
  ]},
  { name: 'Staying alive', cost: 'existential', layers: [
    { name: 'Maintainability', static: 'A lockfile, pinned dependencies and a build in CI. Someone still has to bump the dependencies.', without: 'Nobody can change the site safely.' },
    { name: 'Integrations', static: 'APIs are called at build time, from the browser, or through a function. Each one is another company\'s software.', without: 'CRM, newsletter and analytics are disconnected.', needs: 'Each integration is a dependency' },
    { name: 'Scale & uptime', static: 'Plain files on a CDN. A front-page mention is a non-event.', without: 'A traffic spike takes the site down.' },
  ]},
];

export type Option = { name: string; text: string; href: string };
export type Incident = {
  time: string; title: string;
  vibe: string; wp: string; static: string;
  vibeCode: string; wpCode: string; staticCode: string;
  tryIt?: { label: string; href: string };
  options?: { heading: string; items: Option[] };
};

// Same shape as the original's timeline: a request/response artifact per outcome.
// Artifacts are illustrative unless a "Try it" link says otherwise.
export const incidents: Incident[] = [
  {
    time: '9:02', title: 'Someone asks for the sitemap',
    vibe: 'Missing. Add a prompt, hope the output is valid.', wp: 'SEO plugin generates it.', static: 'Generated by the build. Already there.',
    vibeCode: 'GET /sitemap.xml\n← 404 Not Found', wpCode: 'GET /sitemap_index.xml\n← 200 OK · every page listed', staticCode: 'GET /sitemap-index.xml\n← 200 OK · rebuilt every deploy',
    tryIt: { label: 'Open this site\'s sitemap', href: '/sitemap-index.xml' },
  },
  {
    time: '9:40', title: 'The link is pasted into Slack',
    vibe: 'Grey box, no preview.', wp: 'SEO plugin adds the OG tags.', static: 'OG image rendered at build for every page.',
    vibeCode: '<meta property="og:image">\n← not found · grey box', wpCode: '<meta property="og:image">\n← set by the SEO plugin', staticCode: '<meta property="og:image"\n  content="/og/index.png">  ← built, 1200×630',
    tryIt: { label: 'Open this site\'s share image', href: '/og/index.png' },
  },
  {
    time: '10:15', title: 'A typo in the headline',
    vibe: 'Ask a developer, redeploy, hope nothing else changes.', wp: 'Edit in the admin, publish.', static: 'Edit the Markdown, push, deploy. Or edit through a headless CMS.',
    vibeCode: 'ticket #212 → developer → redeploy', wpCode: 'editor@lumen → Save\n← live in seconds', staticCode: 'edit hero.md → git push\n← live after the next build',
  },
  {
    time: '11:30', title: 'Bots hit the contact form',
    vibe: 'No validation, inbox floods.', wp: 'Forms plugin plus an anti-spam plugin.', static: 'A form service or a bot check in front of one function.',
    vibeCode: 'POST /api/contact × 4,112\n→ inbox: 4,114 new', wpCode: 'POST /contact × 4,112\n→ spam plugin: blocked\n→ entries: 2 saved', staticCode: 'POST /contact × 4,112\n→ honeypot + spam filter: blocked\n→ entries: 2 saved',
    tryIt: { label: 'Try the form, then play the bot', href: '/demo/form' },
    options: {
      heading: 'Your host can already do this',
      items: [
        { name: 'Netlify Forms', text: 'Every submission goes through Akismet. Add a honeypot field, a reCAPTCHA 2, or both, with a couple of attributes on your <form>.', href: 'https://docs.netlify.com/forms/spam-filters/' },
        { name: 'Vercel BotID', text: 'An invisible bot check for the routes you pick, with no visible CAPTCHA. It needs the form sent with fetch, not a plain HTML form action.', href: 'https://vercel.com/docs/botid' },
        { name: 'Cloudflare Turnstile', text: 'A free CAPTCHA alternative. The widget alone does nothing: a function has to verify the token server-side.', href: 'https://developers.cloudflare.com/use-cases/solutions/protect-sensitive-forms-fraud-abuse/' },
      ],
    },
  },
  {
    time: '13:05', title: 'Someone uploads a 14 MB hero photo',
    vibe: 'Served as-is, page crawls.', wp: 'Core makes smaller sizes for you.', static: 'Optimised at build; the original never ships.',
    vibeCode: 'hero.png 14.2 MB\nLCP 9.4s', wpCode: 'hero.jpg → 6 sizes + srcset\n← generated on upload', staticCode: 'hero.png 14.2 MB\n→ hero.avif 96 KB · 5 widths\n← at build, never shipped',
  },
  {
    time: '14:20', title: 'A visitor asks what you track',
    vibe: 'Three trackers nobody remembers adding.', wp: 'Consent plugin, which itself needs updating.', static: 'Nothing loads by default. If marketing wants trackers, a consent library gates them.',
    vibeCode: 'gtag.js loaded · consent: none\npixel.js loaded · consent: none', wpCode: 'gtag.js waiting · consent plugin\n← plugin to keep patched', staticCode: 'analytics.js blocked · consent: none\n← unlocks only on "Accept"',
    tryIt: { label: 'Open the consent + tracking demo', href: '/demo/consent' },
    options: {
      heading: 'Most businesses will want a banner, and Astro has no built-in one',
      items: [
        { name: 'astro-cookieconsent', text: 'A ready Astro integration that wraps vanilla-cookieconsent. One `astro add` and a config object.', href: 'https://github.com/jop-software/astro-cookieconsent' },
        { name: 'vanilla-cookieconsent', text: 'The open-source library underneath, no framework needed. This is what the demo uses. Scripts marked with a category stay inert until accepted.', href: 'https://github.com/orestbida/cookieconsent' },
        { name: 'Hosted consent platforms', text: 'Cookie-Script, CookieChimp and ConsentPro publish Astro setup guides, for teams that need their own dashboard or Google Consent Mode v2 handling.', href: 'https://cookie-script.com/guides/cookie-consent-for-astro' },
        { name: 'Cookieless analytics', text: 'Tools like Plausible or Umami set no cookies. Whether that removes the need for consent depends on your jurisdiction, so ask your lawyer.', href: 'https://plausible.io/data-policy' },
      ],
    },
  },
  {
    time: '16:10', title: 'A critical vulnerability is announced',
    vibe: 'A dependency you did not know you had. Hard to audit.', wp: 'Core is covered. Plugins are on you, and 46% of 2025 vulnerabilities had no patch at disclosure (Patchstack).', static: 'The host serves files; there is no app server of yours to exploit. Build-time dependencies still need updating, and a self-hosted CMS or serverless functions would add some risk back.',
    vibeCode: '$ npm audit\n3 high · 1 critical', wpCode: 'core: security release applied\nplugin: update available\n← you are on call', staticCode: '$ npm audit\nfound 0 vulnerabilities\n← this site, when built',
  },
  {
    time: '17:00', title: 'A visitor mistypes a URL',
    vibe: 'Blank page, visitor gone.', wp: 'Redirect plugin catches it.', static: 'One line in a redirects file, or a real 404 page.',
    vibeCode: 'GET /prodcuts\n← blank page · bounce', wpCode: 'GET /prodcuts\n← 301 → /products', staticCode: 'GET /prodcuts\n← 301 → /',
    tryIt: { label: 'Try /prodcuts on this site', href: '/prodcuts' },
  },
];

export const costs = {
  wp: {
    title: 'WORDPRESS, MONTH 1+',
    items: [
      { item: 'Managed WordPress hosting', range: '$15–$100 / mo' },
      { item: 'Premium licences (SEO, forms add-ons, consent, backup/migration)', range: '$150–$800 / yr' },
      { item: 'Someone to own plugin updates, monitoring and incident response', range: '2–6 hrs / mo' },
      { item: 'Initial build', range: 'Agency quote' },
    ],
    total: 'ask who patches',
  },
  static: {
    title: 'STATIC, MARKDOWN IN GIT',
    items: [
      { item: 'Static hosting + CDN (free tiers exist; check plan terms)', range: '$0–$20 / mo' },
      { item: 'Hosted form endpoint', range: '$0–$20 / mo' },
      { item: 'Cookieless analytics (optional)', range: '$0–$15 / mo' },
      { item: 'Build-time dependency updates (PRs)', range: 'about 1 hr / mo' },
      { item: 'Initial build', range: 'Agency quote' },
    ],
    total: 'the host runs the server',
  },
  cms: {
    title: 'STATIC + HEADLESS CMS',
    items: [
      { item: 'Everything in the static receipt', range: 'see left' },
      { item: 'SaaS CMS plan (seats, content limits)', range: '$0–$300+ / mo' },
      { item: 'or self-hosted CMS: server + database', range: '$5–$50 / mo' },
      { item: 'self-hosted: updates, backups, security', range: 'yours again' },
    ],
    total: 'SaaS: a bill · self-hosted: patching',
  },
  note: 'Illustrative ranges, not quotes. Check your own stack. The point is that "$0.00" leaves out hosting, licences and the person doing the patching, and that adding a CMS to a static site adds a bill or a server to maintain. It is a trade-off, not a free lunch.',
};

export type Vuln = { category: string; finding: string; access: string; open: boolean; source: string; href: string };
// Every row comes from a Patchstack database entry or Patchstack article, read on 2026-10-09.
// Wording follows Patchstack. "Flagged as exploited" is Patchstack's own flag. Patchstack is a security vendor.
export const vulns: Vuln[] = [
  { category: 'WP core', finding: 'July 2026, WordPress up to 7.0.1 (and 6.9.x, 6.8.x): broken access control in the REST API (CVE-2026-63030, CVSS 9.1) plus a SQL injection (CVE-2026-60137, CVSS 9.8), chained for remote code execution. Fixed in 7.0.2, 6.9.5 and 6.8.6. Patchstack saw the first exploitation attempts about 90 minutes after 7.0.2 shipped.', access: 'Anyone, no login needed', open: true, source: 'Patchstack DB', href: 'https://patchstack.com/database/wordpress/wordpress/wordpress/vulnerability/wordpress-core-7-0-1-unauthenticated-remote-code-execution-vulnerability' },
  { category: 'WP core', finding: 'August 2026, WordPress 7.0.3 fixed 12 vulnerabilities, including an unauthenticated reflected XSS on the login screen (CVE-2026-64638) with potential for code execution, several stored XSS issues needing Contributor access, and a multisite privilege escalation.', access: 'Anyone for the login-screen XSS; the rest need a login', open: true, source: 'Patchstack', href: 'https://patchstack.com/articles/wordpress-7-0-3-released-12-vulnerabilities-found-and-fixed/' },
  { category: 'Forms', finding: 'Elementor Pro Forms module, up to 4.2.1: arbitrary file upload that lets an attacker write a PHP file to a public directory (CVE-2026-32475, CVSS 9.0). Fixed in 4.2.2 (19 Aug 2026). Flagged by Patchstack as known to be exploited.', access: 'Anyone, no login needed', open: true, source: 'Patchstack DB', href: 'https://patchstack.com/database/wordpress/plugin/elementor-pro/vulnerability/wordpress-elementor-pro-plugin-4-2-1-arbitrary-file-upload-vulnerability' },
  { category: 'Backups', finding: 'All-in-One WP Migration up to 7.109: unauthenticated second-order SQL injection via archive restore, leading to remote code execution (CVE-2026-19949, CVSS 8.8). Fixed in 7.110 (25 Aug 2026). Flagged by Patchstack as known to be exploited.', access: 'Anyone, no login needed', open: true, source: 'Patchstack DB', href: 'https://patchstack.com/database/wordpress/plugin/all-in-one-wp-migration/vulnerability/wordpress-all-in-one-wp-migration-and-backup-plugin-7-109-unauthenticated-second-order-sql-injection-via-archive-restore-to-remote-code-execution-vulnerability' },
  { category: 'Consent', finding: 'Complianz up to 7.5.4: stored cross-site scripting (CVE-2026-83561, CVSS 7.1), fixed in 7.5.5 (18 Sept 2026). It needs a visitor to click a crafted link or load a crafted page. In July, entries up to 7.5.1 also covered sensitive data exposure, SSRF and PHP object injection; Patchstack\'s list does not show an access level for those.', access: 'Anyone for the XSS; not shown for the July entries', open: true, source: 'Patchstack DB', href: 'https://patchstack.com/database/wordpress/plugin/complianz-gdpr/vulnerabilities' },
  { category: 'SEO', finding: 'Rank Math, late Aug to early Sept 2026, entries affecting versions before 1.0.277: unauthenticated disclosure of non-public post schema and content, and of password-protected post content (before 1.0.277.1), plus several Author+ metadata and content issues and an Editor+ settings change.', access: 'Anyone for the two disclosures; Author+ or Editor+ for the rest', open: true, source: 'Patchstack DB', href: 'https://patchstack.com/database/wordpress/plugin/seo-by-rank-math/vulnerabilities' },
];

export const vulnNote = 'Rows are taken from Patchstack\'s database and articles, read on 2026-10-09. Patchstack is a security vendor, and flags like "known to be exploited" are its own. Entries we could not find there are left out, including the Ninja Forms File Uploads CVE-2026-0740 reported elsewhere. Yoast, All in One SEO and redirect plugins were not checked, which is not a clean bill of health for them.';

export const fairPoints = [
  { title: 'Core was solid in 2025. 2026 has been different.', text: 'Patchstack counted six core vulnerabilities in 2025, all low risk. In 2026 came wp2shell in July and a 12-fix release in August. The core team still shipped the July fix through forced auto-updates within days. That response is what the "dedicated security team" claim is worth, and it is real.' },
{ title: 'A fix is usually out before you read about it.', text: 'Several rows above also include entries that need Author, Editor or Contributor access, and most rows name a fixed version. A patched site is fine.' },
  { title: 'Core updates itself.', text: 'Minor security releases apply automatically. Plugin and theme auto-updates are opt-in, though many hosts turn them on, and since WordPress 6.6 an update that fatals the homepage is rolled back.' },
  { title: 'A managed host changes the picture.', text: 'With a host that patches plugins and monitors the site, much of the cost above becomes someone else\'s job. That is a real service, and it costs money.' },
];

export const staticRisks = [
  { title: 'The npm supply chain is real.', text: 'In September 2025 the Shai-Hulud worm poisoned more than 500 npm packages, and a second wave followed that November. A build that installs a poisoned package can leak tokens. Static hosting does not protect the build.', href: 'https://flashpoint.io/blog/shai-hulud-worm-targeting-npm-supply-chains/', source: 'Flashpoint' },
  { title: '"npm audit: 0" is not "safe".', text: 'The audit only knows about advisories that have been published. It said nothing about a package that was compromised and not yet reported.', href: '', source: '' },
  { title: 'Your build and hosting accounts are the new target.', text: 'Whoever controls your Git repo, CI or hosting login controls your site. Use 2FA, short-lived tokens and least privilege.', href: '', source: '' },
  { title: 'Every service you add is a dependency.', text: 'Forms, analytics, consent and a CMS are other companies\' software. Their outages, price changes and security incidents are yours too.', href: '', source: '' },
];

export const stats = [
  { n: '11,334', label: 'new WordPress vulnerabilities in 2025, up 42%' },
  { n: '91%', label: 'of them in plugins. Only six in core.' },
  { n: '5 h', label: 'median time to first mass exploitation' },
  { n: '46%', label: 'had no patch available at disclosure' },
];

export type Check = { title: string; ask: string; kind: 'links' | 'og' | 'source' | 'term'; links?: { label: string; href: string }[]; code?: string; note?: string };
export const checklist: { group: string; items: Check[] }[] = [
  { group: 'The original six, run against this site', items: [
    { title: 'Sitemap', ask: 'Does it exist and list every page?', kind: 'links', links: [{ label: 'Open /sitemap-index.xml', href: '/sitemap-index.xml' }] },
    { title: '404s & redirects', ask: 'Does a mistyped URL land somewhere useful?', kind: 'links', links: [{ label: 'Try /prodcuts (redirects)', href: '/prodcuts' }, { label: 'Try /no-such-page (404)', href: '/no-such-page' }] },
    { title: 'Open Graph', ask: 'What does the link look like when pasted?', kind: 'og' },
    { title: 'Meta tags', ask: 'Title, description, canonical: are they really in the HTML?', kind: 'source' },
    { title: 'Consent', ask: 'Does anything track before you say yes?', kind: 'links', links: [{ label: 'Open the consent + tracking demo', href: '/demo/consent' }], note: 'This page loads no trackers, so there is nothing to gate here. The demo shows a gated one.' },
    { title: 'Forms', ask: 'Does it reject empty input and bots?', kind: 'links', links: [{ label: 'Try the form, then play the bot', href: '/demo/form' }] },
  ]},
  { group: 'What the original does not check', items: [
    { title: 'Is it patched?', ask: 'Run the audit on what actually ships.', kind: 'term', code: '$ npm audit\nfound 0 vulnerabilities', note: 'Real output from this site, when it was built. It only covers published advisories, so it is a floor, not a guarantee. On WordPress the equivalent is a list of plugins, each with its own vendor and update cadence.' },
    { title: 'What can a stranger reach?', ask: 'Knock on the doors every WordPress site has.', kind: 'links', links: [{ label: 'GET /wp-login.php', href: '/wp-login.php' }, { label: 'GET /xmlrpc.php', href: '/xmlrpc.php' }, { label: 'GET /wp-admin/', href: '/wp-admin/' }], note: 'Static files have no login page, no database and no PHP to attack, so each is a plain 404. The host still has an account and a CDN that someone must secure.' },
  ]},
];

export const matrix = [
  { need: 'Brochure, marketing, docs, blog', pick: 'Static', why: 'Content changes rarely, performance and security matter, nobody needs a login.' },
  { need: 'Non-technical editors publishing daily', pick: 'WordPress or static + headless CMS', why: 'WordPress editing is hard to beat. A headless CMS gives them roles and a friendly editor, but it is one more thing to pay for, and to patch if you self-host it.' },
  { need: 'Shop, memberships, heavy dynamic content', pick: 'WordPress / a real platform', why: 'This is the original\'s home turf and it is right. Static fights you here.' },
  { need: 'Throwaway demo or prototype', pick: 'Vibe it', why: 'It looks done and that is fine, until it ships.' },
  { need: 'Nobody will own updates', pick: 'Static', why: 'Unpatched WordPress decays. Unpatched static files do not run code. A self-hosted CMS would decay too.' },
];
